import images from "./images";
import { COLORS } from "./theme";

const trendingDestinations = [{
        id: 1,
        name: "Mirissa Beach",
        image: images.B1,
        location: "Mirissa, Sri Lanka",
        price: 150,
        reviews: 250,
        rate: 4.5,
        temp: 31,
        date: "11 July",
        env: "Sunny",
        category: [2],
        description: "Mirissa has become the poster child of the Sri Lankan beach scene in recent years, and it’s easy to see why. The beach is a stunning crescent beach of ivory sand bookended by rust-red cliffs. This scenic perfection hasn't gone unnoticed though and is now one of the biggest and busiest beach resorts on the south coast in peak season – think more DJs and cheap drinks than sun loungers and solitude.",
    },
    {
        id: 2,
        name: "Medaketiya Beach",
        image: images.B2,
        location: "Tangalla, Sri Lanka",
        price: 135,
        reviews: 275,
        rate: 2.5,
        temp: 32,
        date: "10 July",
        env: "Sunny",
        category: [2],
        description: "Tangalla has a wonderful end-of-the-line sort of feel to it, being the last ‘resort’ of note as you work your way east along the popular southern coast before hitting the long, wind- and wave-lashed beaches that dominate the southeast of the island. A long sandy beach, Medaketiya is lined with budget guesthouses and laid-back cafes, and is by far the busiest and most developed beach around the town (though compared with beaches elsewhere in southern Sri Lanka it's all very low-key). The sand is golden, but dumping waves can make swimming dangerous at times.",
    },
    {
        id: 3,
        name: "Arugam Bay",
        image: images.B3,
        location: "Arugambay, Sri Lanka",
        price: 125,
        reviews: 225,
        rate: 3,
        temp: 30,
        date: "12 July",
        env: "Sunny",
        category: [2],
        description: "Lovely Arugam Bay, a moon-shaped curl of golden sand, is home to a famed point break that many regard as the best place to surf in the country. With a population of only a few hundred, the town mainly comprises a single road that parallels the coast, flanked by salt-water lagoons. Mellow and relaxed is certainly the vibe here.",
    },
    {
        id: 4,
        name: "Uppuveli Beach",
        image: images.B4,
        location: "Trincomalee, Sri Lanka",
        price: 120,
        reviews: 225,
        rate: 4,
        temp: 29,
        date: "13 July",
        env: "Sunny",
        category: [2],
        description: "Uppuveli, just 6km north from Trincomalee, is a fun little coastal enclave consisting of a fine beach of golden sand, lots of attractive places to stay and eat, and easy access to both historic Trinco and the wildlife haven of Pigeon Island, home to a coral reef that’s great for snorkelling. With an intimate feel and some good-value accommodation, it's easy to see why many travellers call it their favourite spot in the East.",
    },
    {
        id: 5,
        name: "Kirigalpotta",
        image: images.M1,
        location: "Nuwer Eliya, Sri Lanka",
        price: 200,
        reviews: 245,
        rate: 4.5,
        temp: 23,
        date: "11 July",
        env: "Cold",
        category: [1],
        description: "The second highest mountain of Sri Lanka, Kirigalpotta has an altitude of 2,388 meters above the mean sea level. This is also the highest mountain of Sri Lanka which is easily accessible to the common civilians of the nation. Pidurutalagala, on the other hand, is a region of the military base and thus, is not accessible to the public. The peak of Kirigalpotta is located in the Nuwara Eliya district. A 7-kilometer hiking trail which is not very well known leads you to the mountain summit through the Horton Plains National Park. The trail, however, is a splendid adventure for hiking mountains in Sri Lanka.",
    },
    {
        id: 6,
        name: "Pidurutalagala",
        image: images.M2,
        location: "Pidurutalagala, Sri Lanka",
        price: 225,
        reviews: 300,
        rate: 3.5,
        temp: 23,
        date: "12 July",
        env: "Windy",
        category: [1],
        description: "Pidurutalagala is the only ultra prominent peak of this island country. This also happens to be one of the only 1,515 ultra prominent peaks all across the globe. This mountain has a forest reserve in the surrounding location which was subjected to severe damage, five years ago in a forest fire. The fire had caused a loss of more than three acres of forest land. However, with time and the help of the people of Sri Lanka, a lot of the damage has been repaired and is still improving every day. The mountain summit of Pidurutalagala acts as a base of the communications array of the Sri Lankan government and armed forces. It is marked as an ultra-high-security zone due to the confidentiality of the activities in the region.",
    },
    {
        id: 7,
        name: "Thotupola Kanda",
        image: images.M3,
        location: "Hoten Plains, Sri Lanka",
        price: 200,
        reviews: 275,
        rate: 3.5,
        temp: 22,
        date: "13 July",
        env: "Rainy",
        category: [1],
        description: "Thotupola mountain in Sri Lanka is one of the highest-ranking mountains amongst the top ten of the list. This takes around a half day of the journey for climbing and sightseeing. The flora of this region is a contrast to the rest of the mountains of the country. The top of the mountain is the best catch you can get if you have a thing for mountainous greenery. The Thotupola Kanda is one of Sri Lanka’s most famous and beautiful mountains and also happens to have a historical connection to King Ravana Era.",
    },
    {
        id: 8,
        name: " Rassagala",
        image: images.M4,
        location: "Mihinthale, Sri Lanka",
        price: 175,
        reviews: 250,
        rate: 2.5,
        temp: 23,
        date: "15 July",
        env: "Cold",
        category: [1],
        description: "This is commonly referred to as Rajagala Aliso or Rajagalathenna, meaning ‘The Monarchs Rock. Rassagala is a rugged mountain which is heavily forested and has an altitude of 1,038 feet above he mean sea level. This is located in the sparsely populated Eastern province of the country, having an important archeological value. The Rajagala archeological site spreads across 1,600 acres and is the second largest of its kind, the first being the Mihintale monastery in Anuradhapura. This place consists of above six hundred prehistoric ruins, monuments, and artifacts, out of which one could find hundreds of stupas.",
    },
    {
        id: 9,
        name: "Movenpick Hotel Colombo",
        image: images.H1,
        location: "Colombo, Sri Lanka",
        price: 300,
        reviews: 250,
        rate: 4.5,
        temp: 29,
        date: "13 July",
        env: "Sunny",
        category: [3],
        description: "its like other MOvenpick properties across the globe, luxury at its T, services to the P (perfect).. heart melting food, more than comfortable rooms, enjoying city lights.",
    },
    {
        id: 10,
        name: "Amari Galle Safe",
        image: images.H2,
        location: "Hikkaduwa, Sri Lanka",
        price: 275,
        reviews: 225,
        rate: 3.5,
        temp: 31,
        date: "14 July",
        env: "Windy",
        category: [3],
        description: "From the moment you step into reception and are greeted by the beautiful views of the ocean and pool area, you enjoy your welcome coconut water in luxurious lounges overlooking the view Great amenities Fun rooftop...",
    },
    {
        id: 11,
        name: "Le Grand Galle",
        image: images.H3,
        location: "Galle, Sri Lanka",
        price: 250,
        reviews: 200,
        rate: 2.5,
        temp: 28,
        date: "13 July",
        env: "Sunny",
        category: [3],
        description: "Everything in the room was amazing and luxurious.The hotel team is very friendly and kind.We had Breakfast , lunch and dinner at Taste restaurant which was perfect.",
    },
    {
        id: 12,
        name: "Kings Pavilion",
        image: images.H4,
        location: "Kandy, Sri Lanka",
        price: 225,
        reviews: 175,
        rate: 2,
        temp: 27,
        date: "12 July",
        env: "Rainy",
        category: [3],
        description: "The staff were brilliant, kind and thoughtful and are very happy to arrange luxury transfers at very sensible prices.",
    },
]

const categories = [{
        id: 1,
        name: "Mountain",
        image: images.mountain,
        color: COLORS.darkGreen,
    },
    {
        id: 2,
        name: "Beach",
        image: images.beach1,
        color: COLORS.blue,
    },
    {
        id: 3,
        name: "Hotel",
        image: images.hotel1,
        color: COLORS.darkPink,
    },
]

export default {
    trendingDestinations,
    categories
}